### ISSUE TITLE
[kirkstone] zero2w rpi-test-image

### ISSUE THREAD

**Issue by jwinarske** [agherzan/meta-raspberrypi#1060] opened 2022-05-04 16:18 UTC
**Description**

Branch: Kirkstone

i2c, SPI, and wifi are not coming up.

One thing I notice is:
https://github.com/agherzan/meta-raspberrypi/blob/master/conf/machine/raspberrypi0-2w-64.conf#L16
Shouldn't this be `broadcom/bcm2710-rpi-zero-2-w.dtb` ?

My local.conf is here:
https://github.com/jwinarske/manifests/blob/kirkstone/conf/rpi64_config#L28

**Comment by kraj** [comment] 2022-05-04 17:37
> @agherzan the kirkstone branch need to sync with master; the `kmod` change should fix this.

Fix is in oe-core kirkstone-next please use that branch

**Comment by otavio** [comment] 2022-05-04 17:40
Where? Checking https://github.com/openembedded/openembedded-core/compare/kirkstone...kirkstone-next doesn't show nothing related.

**Comment by kraj** [comment] 2022-05-04 19:53
Maybe Steve did not yet push it but it’s on its way we should revert the fix that @agherzan pushed to meta rpi master As well

**Comment by kraj** [comment] 2022-05-04 19:55
See https://git.yoctoproject.org/poky-contrib/log/?h=stable/kirkstone-nut

**Comment by otavio** [comment] 2022-05-04 20:01
I saw the change on master; for now, I'll disable it in kirkstone.

**Comment by agherzan** [comment] 2022-05-04 21:54
https://github.com/agherzan/meta-raspberrypi/pull/1061

**Comment by jwinarske** [comment] 2022-05-04 22:23
@kraj Which repo to kirkstone-next?  I moved oe-core to kirkstone-next with no change.  Moving poky to kirkstone-next results in a build break.

Manifest:
https://github.com/jwinarske/manifests/blob/kirkstone/rpi64.xml

**Comment by smjaberl** [comment] 2022-05-13 18:39
Hi, is there a solution in sight? 

My build config is this:
Build Configuration:
BB_VERSION           = "2.0.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "raspberrypi0-2w-64"
DISTRO               = "poky"
DISTRO_VERSION       = "4.0.1"
TUNE_FEATURES        = "aarch64 armv8a crc cortexa53"
TARGET_FPU           = ""
meta                 
meta-poky            = "kirkstone:8941afebd18387de133722fddfbcfc871c3b3b91"
meta-raspberrypi     = "kirkstone:0135a02ea577bd39dd552236ead2c5894d89da1d"
meta-oe              
meta-python          
meta-networking      = "kirkstone:5357c7a40eaf8d1bcf7ff58edbba8e9527e40c7d"

And if I boot the image there is no wlan0:


![photo_2022-05-13_20-36-50](https://user-images.githubusercontent.com/13895368/168346342-b314055f-20c2-4206-871f-af2194caead7.jpg)

**Comment by agherzan** [comment] 2022-05-16 08:49
@smjaberl the fix is now merged in kirkstone oe-core. Closing this issue.

**Closed by agherzan** 2022-05-16 08:49 UTC
Labels: type/bug, meta-raspberrypi/master

**Comment by smjaberl** [comment] 2022-05-16 16:01
@agherzan: Sorry, I as an experienced programmer, but newbie to yocto, don't know what exactly you mean by kirkstone oe-core. Is this the meta-openembedded branch or the meta-raspberry branch?

Here is my build config, I pulled today all three branches: 
`meta-poky            = "kirkstone:8c489602f218bcf21de0d3c9f8cf620ea5f06430"`
`meta-raspberrypi     = "kirkstone:0135a02ea577bd39dd552236ead2c5894d89da1d"`
`meta-oe              `
`meta-python          `
`meta-networking      = "kirkstone:5357c7a40eaf8d1bcf7ff58edbba8e9527e40c7d"`

The issue is still the same. 

regards!

**Comment by agherzan** [comment] 2022-05-17 11:34
I was referring to updating oe-core/poky to the current HEAD of kirkstone. The revision you have there for meta-poky includes the fix. Are you using poky for the core layer too?

**Comment by smjaberl** [comment] 2022-05-17 23:20
Well, my own bb file is this: 

```
require recipes-core/images/core-image-minimal.bb

IMAGE_INSTALL += "libstdc++ mtd-utils"
IMAGE_INSTALL += "openssh openssl openssh-sftp-server" 
IMAGE_INSTALL += "python3 python3-django python3-djangorestframework"
IMAGE_INSTALL += " linux-firmware-bcm43430 bluez5 wpa-supplicant"
```

So it is based on the poky core-image-minimal. In the local.conf I defined the rpi-zero2, so I think the wifi driver should be in my system. 

```
MACHINE ??= "raspberrypi0-2w-64"

DISTRO_FEATURES += "systemd wifi ipv4 bluez5 bluetooth "
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
COMBINED_FEATURES += "wifi"
```

**Comment by agherzan** [comment] 2022-05-18 16:56
Thanks for confirming @jwinarske.
