### ISSUE TITLE
Error Licence 

### ISSUE THREAD

**Issue by MonsieurHBA** [agherzan/meta-raspberrypi#1032] opened 2022-03-09 12:55 UTC
![error](https://user-images.githubusercontent.com/91086501/157445745-7f22f85f-d902-4f8d-8474-4c8571e84094.png)

**Comment by agherzan** [comment] 2022-03-14 13:58
I've just tried to replicate this using `rpi-hwup-image` target and I couldn't reproduce the errors above. Here is the LICENSE value inherited from core:

```
$ bitbake-getvar -r rpi-hwup-image LICENSE
#
# $LICENSE [4 operations]
#   set /[...]/bitbake.conf:294
#     [_defaultval] "INVALID"
#   set /[...]/documentation.conf:268
#     [doc] "The list of source licenses for the recipe. Logical operators '&' or '|' and parentheses can be used."
#   set /[...]/core-image-minimal.bb:7
#     "MIT"
#   set? /[...]/image.bbclass:25
#     "MIT"
# pre-expansion value:
#   "MIT"
LICENSE="MIT"
```

You will need to provide a clean way to reproduce including layer versions, OS etc. Please keep the issue template next time and prefer text logs as opposed to screenshots - you can understand how hard is to handle an image for logs. I'll close this for now.

**Closed by agherzan** 2022-03-14 13:58 UTC
